"""add users table and per-user applications

Revision ID: 8530cf629a71
Revises: 47b612672f6f
Create Date: 2026-07-08 17:48:29.892793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8530cf629a71'
down_revision: Union[str, Sequence[str], None] = '47b612672f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # Applications created before the user system belong to no account and
    # cannot be backfilled with a real owner, so they are cleared here. This
    # lets us add a NOT NULL user_id safely on existing databases.
    op.execute('DELETE FROM applications')
    op.add_column('applications', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('applications_job_id_key'), 'applications', type_='unique')
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_unique_constraint('uq_applications_user_job', 'applications', ['user_id', 'job_id'])
    op.create_foreign_key(
        'fk_applications_user_id', 'applications', 'users',
        ['user_id'], ['id'], ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_applications_user_id', 'applications', type_='foreignkey')
    op.drop_constraint('uq_applications_user_job', 'applications', type_='unique')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.create_unique_constraint(op.f('applications_job_id_key'), 'applications', ['job_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('applications', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
